### PR TITLE
Increase client RECV_BUFF size to 1 MB

### PR DESCRIPTION
**Pull request by ahuazuipiaoliang**
## Related Issues & PRs
https://github.com/ouster-lidar/ouster-ros/issues/190
## Summary of Changes
increase buffer size
## Validation
Tested with my LiDAR

### CODE REVIEW

**Comment by Samahu** [comment]
@ahuazuipiaoliang Thanks for submitting the PR, this is rather a known issue to us and increasing the RECV_BUFF size is needed. 1 MB seems to be the minimum value to resolve the issue. Since this involves the main the SDK and the ROS driver this involves some process to get it merged. Note that in order for this fix to work it also requires to increase network reception as I noted before: buffer https://github.com/ouster-lidar/ouster-ros/issues/190#issuecomment-1675273573. I will circle back with you on merging the fix soon.

**Comment by ahuazuipiaoliang** [comment]
@Samahu I've already modified the network reception but it didn't work, after modifying the `RCVBUF_SIZE`, it worked.

**Comment by Samahu** [comment]
I was trying to say that you would need both things to be done, at least for some of the devices that I tested. You could verify that by resetting the size of network reception.

**Comment by Samahu** [comment]
Incorporated the changes into PR #548 to be able to edit before merge (since maintainers weren't given permission to edit the PR).

**Pull request closed without merging**
