### PR TITLE
add install commands

### PR DESCRIPTION
**Pull request by lsolanka**
This patch adds installation targets for libraries, executables and the launch file.

### CODE REVIEW

**Comment by dgarbuzov** [comment]
The sample code in ouster_client and ouster_viz needs to build and run without ROS installed, so using ${CATKIN_PACKAGE_LIB_DESTINATION} wouldn't work. We can add the install directives to just ouster_ros/CMakeLists.txt, which would be enough to make a package to run the ros nodes outside of the build tree -- would that be enough?

**Comment by asherikov** [comment]
It is possible to check if the project is build with catkin in CMakeLists, e.g.:
```
if (DEFINED CATKIN_DEVEL_PREFIX)
endif()
```

**Comment by lsolanka** [comment]
> It is possible to check if the project is build with catkin in CMakeLists, e.g.:
> 
> ```
> if (DEFINED CATKIN_DEVEL_PREFIX)
> endif()
> ```

Yes, that would be my preferred solution then. @dgarbuzov does this sound fine to you? If yes I can update the patch.

**Comment by dgarbuzov** [comment]
@lsolanka that should be fine, but before we do that I'm curious how you want to use the targets from ouster_client and ouster_viz. The libraries (ouster_client, ouster_ros, ouster_viz) are statically linked into the ROS nodes, and aren't otherwise usable without also installing the headers. The ouster_client_example binary is only meant for use in development, and the functionality of the 'viz' executable is redundant with 'viz_node' if you're already using the ROS code.

So, to me it seems like only the os1_node, os1_cloud_node, viz_node, and img_node targets would potentially be useful to install, unless I'm misunderstanding how you're using the sample code.

**Comment by dgarbuzov** [comment]
Thanks for the contribution -- the latest commit has install directives for the ROS nodes. Let me know if that doesn't address your usecase.

**Pull request closed without merging**
