### PR TITLE
Lidar deskewing based on motion 

### PR DESCRIPTION
**Pull request by matlabbe**
A new parameter `fixed_frame_id` has been added to `os_cloud_node`: 
* If this parameter is empty (default), the lidar scan will be converted to PointCloud2 using the original `scan_to_cloud` function. 
* If this parameter is not empty, that frame will be used to get the motion of the lidar while the ouster is doing 1 rotation, then transforming each individual point based on that motion. A second `scan_to_cloud` function has been added with a TfListener to get that motion. 
    * Advantage: If the sensor is moved fast, it will help **a lot** to remove point cloud distortion caused by the motion. For example, if the ouster is placed on a robotic arm moving pretty fast, as long as you know accuratly that arm position (through TF), you can remove any distortion in the resulting point cloud. 
    * Disadvantage: The os_cloud_node requires 9% more CPU on my computer (normally 20% CPU) with OS0 at 10Hz.

### CODE REVIEW

**Comment by matlabbe** [comment]
I added a new commit above with new parameter called `wait_for_transform` to be able to wait a little time (default 10 ms) for valid TF before doing the deskewing.

**Comment by peci1** [comment]
Calling lookupTransform for each column of the scan is plain resource wasting. These calls are not as fast as you think, so it could introduce unwanted delay to the lidar driver. You can get inspired by the code in https://github.com/ros-perception/laser_geometry/blob/dad4c7d6f4db679069583d84944cdfa334854061/src/laser_geometry.cpp#L190 to use interpolation (you could use more interpolation points than just start and end time of scan if you think the motion was very fast).

**Comment by matlabbe** [comment]
Yes, it was the "disadvantage" I referred. On our system, it work pretty well though. The only thing **I could check is how much time is required to transform the point cloud**, it should be at least faster than doing one rotation of the lidar, otherwise there could be latency and even packets lost (the [queue_size](https://github.com/ouster-lidar/ouster_example/blob/b8b23c35d7b719d69341a438d386a801688aa6a4/ouster_ros/src/os_cloud_node.cpp#L80-L83) of the lidar and imu subscribers should be large enough to buffer them while we are transforming the cloud). 

I checked [velodyne_pointcloud](https://github.com/ros-drivers/velodyne/blob/3817b357df0033ff1faa67578217e6494ff47cb9/velodyne_pointcloud/include/velodyne_pointcloud/datacontainerbase.h#L187-L220), they also use lookuptransform to transform individual points in order to [deskew the lidar](https://github.com/ros-drivers/velodyne/blob/7c2f199f552ecb9f58a3c30734681042b1b99f82/velodyne_pointcloud/src/conversions/transform.cc#L133-L135). TF is doing all the interpolation. In [laser_geometry](https://github.com/ros-perception/laser_geometry/blob/dad4c7d6f4db679069583d84944cdfa334854061/src/laser_geometry.cpp#L260) or [lidar_deskew](https://github.com/rsasaki0109/laser_deskew/blob/173091fe10f685d8ea21529098b9e13225bb924b/src/laser_deskew.cpp#L90), they interpolate only between the first and last stamp, which is not reliable if you set the ouster at 10 Hz and if your robot does some non-linear jerky moves (collision, drone having fast change in orientation, fast industrial arm... ). For a car moving relatively at the same speed during 100 ms, this may not be a problem interpolating between first and last stamps, though if the car drive on a pothole, this could cause some strange distortions in the resulting point cloud. As you said, one tradeoff would be to use lookuptransform less often. For example, instead of taking only first and last stamp, we use also middle stamp... we could split more the time like that to be more accurate but slower (the slower but higher accuracy case would be the current version doing a lookuptransform for every column in the scan).

**Comment by dgarbuzov** [comment]
Would be happy to point users to some third-party deskewing code in the docs as an alternative to the general-purpose ROS packages above, if it has some advantages. Unfortunately, right now, I don't think we should try to provide it as part of the driver, though this PR would be a good starting point.

Other than improved interpolation, it should be possible to squeeze out some performance by transforming a column at a time, for example -- though I'm not sure how feasible that is with PCL data structures.

Making it easier to minimize latency in downstream code (e.g. by publishing partial point clouds) has also come up before, if anyone has any suggestions.

**Comment by matlabbe** [comment]
The approach of the pull request has been implemented in a independent nodelet (compatible also with velodyne and robosense point clouds) called `rtabmap_util/lidar_deskewing`: http://wiki.ros.org/rtabmap_util#rtabmap_util.2Flidar_deskewing

**Pull request closed without merging**
