### PR TITLE
Added multicast support

### PR DESCRIPTION
**Pull request by ShepelIlya**
Added multicast support of ouster sensors.
Tested with OS1-32 Rev. D and OS0-64 Rev. D.

### CODE REVIEW

**Comment by ShepelIlya** [comment]
@dgarbuzov can you look at this?

**Comment by yt** [comment]
Tested with joining to a multicast group `ip addr add 239.1.0.1 dev myINT autojoin` 
PR seems to be working fine.

**Comment by ShepelIlya** [comment]
Example how to launch it described in [comment](https://github.com/ouster-lidar/ouster_example/issues/277#issuecomment-900605637)

**Comment by dgarbuzov** [comment]
Kind of surprised people are using multicast UDP with ROS. Can you tell me more about the use case? I would have thought either using the ROS message bus or UDP broadcast (which doesn't require any client-side configuration) would be way easier.

Seems like at least a few users are interested but, in general, I'm inclined to invest in making it easier to reuse some of the client code (e.g. by letting the user pass in a socket) vs. trying to support more configuration directly. We're still missing some basics (like binding to a specified local address!), and socket API differences between platforms have been a bit of a pain point.

**Comment by ShepelIlya** [comment]
Yeah, we are using three ousters on our robot at the same time, and we need to work with their data on three different Jetsons. Our experience shows that multicast works much better in this case then sending clouds as ROS messages with 1 ROS master.

**Comment by freol35241** [comment]
I would be interested in this as well, also looking at listening in on a single ouster from multiple applications/processing units. It seems however that this PR lacks a corresponding update of the python interface?

**Comment by ShepelIlya** [comment]
Hello @Samahu! We still use source code from this PR to listening ouster traffic on several Jetson Xaviers and sometimes we merge master branch from this repo to our fork.
Also we are testing our version of ROS2 driver with multicast support now.
May be we can update and refactor this code and merge it to master branch? Are you still interested in this PR?
In that case process of merging original updates from this repo to our fork will be much easier for us and this feature will be available for community.

**Comment by Samahu** [comment]
@ShepelIlya, I am personally up for it and will help getting this through if you create a new PR/MR. One thing I would recommend is that keep the original two `init_clients` API intact and create a third one specific to the MTU case. It would be much easier this way as it would break the code for users who depend on any of the existing two variants of the API. another thing is ouster-ros has moved to a separate repo which I believe you are aware of. But that means you would need to create submit two PRs to have this functionality introduced.

**Comment by ShepelIlya** [comment]
> @ShepelIlya, I am personally up for it and will help getting this through if you create a new PR/MR. One thing I would recommend which is to keep the original two `init_clients` API intact and create a third one specific to the multicast case. It would be much easier this way as it wouldn't break the code for users who depend on any of the existing two variants of the API. another thing is ouster-ros has moved to a separate repo which I believe you are aware of. But that means you would need to create submit two PRs to have this functionality introduced.

Ok, i'll try to do it at this weekend.

**Comment by ShepelIlya** [comment]
I opened a new [PR](#480) for sdk and for [ros_driver](https://github.com/ouster-lidar/ouster-ros/pull/57).
@Samahu I think that we can close this PR now.

**Comment by Samahu** [comment]
> I opened a new [PR](https://github.com/ouster-lidar/ouster_example/pull/480) for sdk and for [ros_driver](https://github.com/ouster-lidar/ouster-ros/pull/57). @Samahu I think that we can close this PR now.
> 
> Please check it, if it needs some fixes or improvements. Also we use several custom features in our fork of ouster driver, and if you interested i can make PR for any of them. They are:
> 
> * Nodelet in ouster_ros codestyle for merging clouds from several sensors to one (based on [ROS ApproximateTimePolicy](wiki.ros.org/message_filters))
> * Box filter for filtering cloud at driver side and make dense PointCloud2, what is useful if we need to filter points  reflecting from ego robot. (For example on our setup we filter approximately 2000-4000 points which makes the message size noticeably smaller). With this filter we use additional ROS parameter with frame form TF Tree, where we need to filter points (its useful if lidar orientation differs from ego robot and you want to publish filtered points in ego robot frame).
> * Additional ROS flags for publishing imu msgs/transforms to TF Tree (for decreasing CPU utilization).

I will try to follow on your proposed list of change as time permits.

For now I will close this PR in favor of #480 and https://github.com/ouster-lidar/ouster-ros/pull/57

**Pull request closed without merging**
