### PR TITLE
First commit for Autoware version branch

### PR DESCRIPTION
**Pull request by alexandrx**
First commit for Autoware version branch. Modified the original Ouster ROS code to suit Autoware needs. Code structure is more simple, only ROS driver code is kept, and the `readme.md` file has more details on how to configure the sensor and use this driver. To further ease Autoware integration, Velodyne compatibility options were added and tested with `ndt_matching`, `ray_ground_filter` and `euclidean_cluster` nodes.

### CODE REVIEW

**Comment by alexandrx** [comment]
Sorry, I was supposed to place a PR at a the fork.

**Comment by alexandrx** [comment]
Please consider this proposed branch.

**Comment by geg58** [comment]
looks like a timing issue - I tested on lidar mode 2048x10

**Comment by geg58** [comment]
looks like these changes fixed the timing issue: https://github.com/CPFL/ouster/pull/2

**Comment by amc-nu** [comment]
@geg58 
We would like to stop using our fork, and switch to the upstream code. 

Do you find any issue with this PR? We've also tested with the Ouster-1 extensively.

Is there something else we can do to get this merged?

**Comment by dgarbuzov** [comment]
Thanks for the contribution! Unfortunately, this would be hard to merge since it deletes the client and viz subdirectories. We would welcome some of the enhancements as separate, self-contained PRs, if possible.

**Pull request closed without merging**
