### PR TITLE
add libproj-dev to the dependencies list

### PR DESCRIPTION
**Pull request by Ubiquite**

### CODE REVIEW

**Comment by dgarbuzov** [comment]
I'm not sure this is a dependency -- it's not present on any of the systems I've tested on. Was there a particular build error that was fixed when you added it?

**Comment by Ubiquite** [comment]
I couldn't link without it, it was looking for libproj.so

**Comment by Ubiquite** [comment]
with ubuntu 16.04 amd64

**Comment by dgarbuzov** [comment]
Hmm, wonder what's different about our systems. As far as I can tell, libproj isn't linked in when I build viz

$ ldd viz
	linux-vdso.so.1 =>  (0x00007ffd8b5e1000)
	libvtkInteractionStyle-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkInteractionStyle-6.2.so.6.2 (0x00007fb8d9ba4000)
	libvtkRenderingOpenGL-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkRenderingOpenGL-6.2.so.6.2 (0x00007fb8d96fc000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fb8d94df000)
	libvtkRenderingCore-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkRenderingCore-6.2.so.6.2 (0x00007fb8d904b000)
	libvtkImagingCore-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkImagingCore-6.2.so.6.2 (0x00007fb8d8c6e000)
	libvtkCommonExecutionModel-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkCommonExecutionModel-6.2.so.6.2 (0x00007fb8d89c0000)
	libvtkCommonDataModel-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkCommonDataModel-6.2.so.6.2 (0x00007fb8d8451000)
	libvtkCommonTransforms-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkCommonTransforms-6.2.so.6.2 (0x00007fb8d8222000)
	libvtkCommonCore-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkCommonCore-6.2.so.6.2 (0x00007fb8d7cf4000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fb8d7972000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fb8d7669000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fb8d7453000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb8d7089000)
	libvtkFiltersSources-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkFiltersSources-6.2.so.6.2 (0x00007fb8d6dc3000)
	libvtkFiltersExtraction-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkFiltersExtraction-6.2.so.6.2 (0x00007fb8d6aae000)
	libvtkCommonMath-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkCommonMath-6.2.so.6.2 (0x00007fb8d688c000)
	libvtkImagingHybrid-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkImagingHybrid-6.2.so.6.2 (0x00007fb8d6622000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007fb8d63ae000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fb8d6074000)
	libXt.so.6 => /usr/lib/x86_64-linux-gnu/libXt.so.6 (0x00007fb8d5e0b000)
	libvtkIOImage-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkIOImage-6.2.so.6.2 (0x00007fb8d5aa4000)
	libvtkCommonSystem-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkCommonSystem-6.2.so.6.2 (0x00007fb8d5890000)
	libvtksys-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtksys-6.2.so.6.2 (0x00007fb8d564b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb8d9e30000)
	libvtkCommonColor-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkCommonColor-6.2.so.6.2 (0x00007fb8d542f000)
	libvtkFiltersGeometry-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkFiltersGeometry-6.2.so.6.2 (0x00007fb8d51a0000)
	libvtkFiltersGeneral-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkFiltersGeneral-6.2.so.6.2 (0x00007fb8d4c75000)
	libvtkCommonComputationalGeometry-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkCommonComputationalGeometry-6.2.so.6.2 (0x00007fb8d4a37000)
	libvtkFiltersCore-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkFiltersCore-6.2.so.6.2 (0x00007fb8d4479000)
	libvtkCommonMisc-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkCommonMisc-6.2.so.6.2 (0x00007fb8d4263000)
	libvtkFiltersStatistics-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkFiltersStatistics-6.2.so.6.2 (0x00007fb8d3fd7000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fb8d3dbd000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fb8d3b94000)
	libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007fb8d3991000)
	libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007fb8d378e000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007fb8d3587000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007fb8d3384000)
	libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007fb8d3153000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fb8d2f41000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007fb8d2d3e000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fb8d2b38000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007fb8d2936000)
	libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007fb8d271d000)
	libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007fb8d2518000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fb8d22f6000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007fb8d20f0000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007fb8d1ede000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fb8d1cda000)
	libSM.so.6 => /usr/lib/x86_64-linux-gnu/libSM.so.6 (0x00007fb8d1ad2000)
	libICE.so.6 => /usr/lib/x86_64-linux-gnu/libICE.so.6 (0x00007fb8d18b8000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007fb8d165f000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fb8d143a000)
	libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007fb8d11c6000)
	libvtkmetaio-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkmetaio-6.2.so.6.2 (0x00007fb8d0f31000)
	libvtkDICOMParser-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkDICOMParser-6.2.so.6.2 (0x00007fb8d0d19000)
	libvtkImagingFourier-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkImagingFourier-6.2.so.6.2 (0x00007fb8d0aea000)
	libvtkalglib-6.2.so.6.2 => /usr/lib/x86_64-linux-gnu/libvtkalglib-6.2.so.6.2 (0x00007fb8d08c7000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fb8d06c3000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fb8d04bd000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fb8d02b8000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fb8d0096000)

**Comment by dgarbuzov** [comment]
A couple of more things to check:
- are you building with libvtk5-dev or libvtk6-dev?
- libproj9 actually gets pulled in as a transitive dependency of libvtk6-dev. The CMakeLists.txt for ouster_viz was recently updated to link only the required vtk modules. While it wasn't getting linked in for me before, it might be worth another try with the update.

Thanks!

**Comment by Ubiquite** [comment]
I'm linking with libvtk6-dev

**Comment by Ubiquite** [comment]
> A couple of more things to check:
> 
> * are you building with libvtk5-dev or libvtk6-dev?
> * libproj9 actually gets pulled in as a transitive dependency of libvtk6-dev. The CMakeLists.txt for ouster_viz was recently updated to link only the required vtk modules. While it wasn't getting linked in for me before, it might be worth another try with the update.
> 
> Thanks!

Okey I can build without libproj-dev after a pull

**Pull request closed without merging**
