### PR TITLE
Update for FW 2.4. See changelog for details

### PR DESCRIPTION
**Pull request by kairenw**
* Drop support for Ubuntu 16.04, ROS kinetic
* Drop support for sensors on FW < 2.0
* Require C++ 14 for build
* Use sensor http interface for sensors on FW 2.1+
* Switch from nodes to nodelets in ouster_ros
* Separate ROS launch files for play, replay, and record
* Add new experimental ROS config services set_config and get_config
* Bugfixes. See Changelog

### CODE REVIEW

**Review by Samahu — APPROVED** [review]

**Review by chrisbayruns — APPROVED** [review]

**Review by bexcite — APPROVED** [review]

**Comment by Samahu** [comment]
@kairenw we forgot to advertise the new `TIME_FROM_ROS_TIME` option and include it into the release note

**Comment by kairenw** [comment]
whoops! good catch

**Comment by peci1** [comment]
This doesn't make any sense:

https://github.com/ouster-lidar/ouster_example/blob/master/ouster_ros/CMakeLists.txt#L56-L64

There are no targets called  `nodelet_os_cloud` and `nodelet_os_image`. I guess this will completely break any library depending on ouster_ros because it would be searching for these nonexisting .so files. Also, you call `catkin_package` three times in the CMakeLists.txt. That is also highly unusual (I even wonder it works).

**Comment by peci1** [comment]
In ouster_ros, you also have to install the nodelets_os.xml file to the package share destination.

**Comment by Samahu** [comment]
@peci1 You are absolutely right, we should have revised these statements when we switched from nodes to notelets.

**Comment by Samahu** [comment]
@peci1 the issues you reported about the FW 2.4 release have been addressed as part of #425 pull request. Always let us know of any problems that you may find.

**Pull request merged**
