### PR TITLE
add BUILD_VIZ option to ROS cmake

### PR DESCRIPTION
**Pull request by amaizr**
add `BUILD_VIZ` support to ROS cmake, defaulting to `ON`. This allows viz disable w/:

```shell
$ catkin_make -DBUILD_VIZ=OFF
```

### CODE REVIEW

**Comment by dgarbuzov** [comment]
Can you explain a bit about your use case -- Is this to avoid the runtime dependency on GL / X11? For running ROS on a headless system maybe?

**Comment by amaizr** [comment]
Yes that's right: I'm creating arm64 builds in an env that doesn't have `GLEW` or `glfw3` for deployment to a headless nvidia tx2 robotic system.

**Comment by dgarbuzov** [comment]
actually I'm inclined to just remove viz_node. Not sure what it really adds as example code. I'm sure most ROS users just want to use rviz anyway.

**Comment by dgarbuzov** [comment]
should be addressed in #259

**Pull request closed without merging**
